import fs from 'fs';
import path from 'path';

const DOC_FILES = [
  'docs/application.md',
  'docs/business-rules.md',
  'docs/templates.md',
  'docs/overview.md',
];

const MAX_CONTEXT_CHARS = 40_000;

export interface DocsContext {
  text: string;
  included: string[];
}

/**
 * Loads the project documentation generated by the other cli-doc-ai modes,
 * so it can be used as ground truth for task enrichment.
 */
export function loadDocsContext(cwd: string): DocsContext {
  const included: string[] = [];
  const parts: string[] = [];
  let remaining = MAX_CONTEXT_CHARS;

  for (const relPath of DOC_FILES) {
    if (remaining <= 0) break;

    const fullPath = path.resolve(cwd, relPath);
    if (!fs.existsSync(fullPath)) continue;

    const content = fs.readFileSync(fullPath, 'utf-8').slice(0, remaining);
    included.push(relPath);
    parts.push(`## ${relPath}\n\n${content}`);
    remaining -= content.length;
  }

  return { text: parts.join('\n\n---\n\n'), included };
}
